<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>io.ianw.GameFrame</PackageId>
    <Title>GameFrame</Title>
    <Authors>Ian Wiggins</Authors>
    <Company>ianw.io</Company>
    <Product>GameFrame</Product>
    <Description>A monogame framework for quickly building dynamic 2D games using an extensible component library.</Description>
    <Copyright>2024 Ian Wiggins</Copyright>
    <PackageProjectUrl>https://gameframe.ianw.io</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>game;game engine;monogame</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/iWiggins/GameFrame</RepositoryUrl>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="README.md" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Core\Clickables\Clickables.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Clickables.tt</DependentUpon>
    </Compile>
    <Compile Update="Core\Geometrics\Geometrics.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Geometrics.tt</DependentUpon>
    </Compile>
    <Compile Update="Core\Input\KeyboardKeys.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>KeyboardKeys.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Core\Clickables\Clickables.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Clickables.cs</LastGenOutput>
    </None>
    <None Update="Core\Geometrics\Geometrics.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Geometrics.cs</LastGenOutput>
    </None>
    <None Update="Core\Input\KeyboardKeys.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>KeyboardKeys.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>