<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Core\Clickables\Clickables.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Clickables.cs</LastGenOutput>
    </None>
    <None Update="Core\Geometrics\Geometrics.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Geometrics.cs</LastGenOutput>
    </None>
    <None Update="Core\Input\KeyboardKeys.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>KeyboardKeys.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>